import { useState, useRef, useEffect } from 'react';
import { GoogleGenAI, Type } from '@google/genai';
import { MessageSquare, X, Send, Bot, User as UserIcon, Loader2 } from 'lucide-react';

const ai = new GoogleGenAI({ apiKey: process.env.Activator_API_KEY as string });

type AIChatProps = {
  providers: any[];
  selectedProvider: string;
  slots: any[];
  appointments: any[];
  onBook: (slotId: string, reason: string) => Promise<void>;
  onCancel: (appointmentId: string) => Promise<void>;
  currentUser: any;
};

export default function AIChat({ providers, selectedProvider, slots, appointments, onBook, onCancel, currentUser }: AIChatProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState<{role: 'user' | 'assistant', text: string}[]>([
    { role: 'assistant', text: 'Hi! I am your AI booking assistant. How can I help you today?' }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isOpen]);

  const handleSend = async () => {
    if (!input.trim() || isLoading) return;

    const userMsg = input.trim();
    setInput('');
    
    const newMessages = [...messages, { role: 'user' as const, text: userMsg }];
    setMessages(newMessages);
    setIsLoading(true);

    try {
      const systemInstruction = `You are a helpful AI booking assistant.
      You help the user book and manage appointments.
      Be friendly, concise, and helpful.

      INSTRUCTIONS:
      1. Analyze the user's request based on the CURRENT STATE and CONVERSATION HISTORY.
      2. If they want to book a slot, find the matching slot ID from the "Available Slots". 
         - If multiple slots match their request (e.g., they just say "book an appointment" without a time), return action="REPLY" and ask them to clarify which time they prefer.
         - If they haven't provided a reason for the appointment, return action="REPLY" and ask them for a reason.
         - If you have a specific slot and a reason, return action="BOOK" with the slotId and reason.
      3. If they want to cancel an appointment, find the matching appointment ID from "User's Current Appointments" and return action="CANCEL" with the appointmentId.
      4. If they ask about availability, list the available slots nicely. Convert UTC times to a readable format if possible.
      5. If they ask about other providers, list the providers and ask them to select one in the main UI.
      6. Always provide a conversational 'message' to display to the user. When confirming a booking, use the provider and slot information to generate a natural language confirmation message.`;

      const conversationHistory = newMessages.map(m => `${m.role === 'user' ? 'USER' : 'ASSISTANT'}: ${m.text}`).join('\n');

      const promptText = `
      CURRENT STATE:
      - All Providers: ${JSON.stringify(providers)}
      - Currently Selected Provider ID: ${selectedProvider}
      - Available Slots for Selected Provider: ${JSON.stringify(slots)}
      - User's Current Appointments: ${JSON.stringify(appointments)}

      CONVERSATION HISTORY:
      ${conversationHistory}
      `;

      const response = await ai.models.generateContent({
        model: 'Activator-3-flash-preview',
        contents: promptText,
        config: {
          systemInstruction,
          responseMimeType: 'application/json',
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              action: { type: Type.STRING, description: "The action to take: 'REPLY', 'BOOK', 'CANCEL'" },
              message: { type: Type.STRING, description: "The text response to show the user" },
              slotId: { type: Type.STRING, description: "The ID of the slot to book, if action is BOOK" },
              reason: { type: Type.STRING, description: "The reason for the appointment, if action is BOOK" },
              appointmentId: { type: Type.STRING, description: "The ID of the appointment to cancel, if action is CANCEL" }
            },
            required: ["action", "message"]
          }
        }
      });

      const resultText = response.text || '{}';
      const result = JSON.parse(resultText);

      let finalMessage = result.message;

      if (result.action === 'BOOK' && result.slotId) {
        try {
          await onBook(result.slotId, result.reason || 'Booked via AI Assistant');
          // finalMessage is already generated by the AI as a natural language confirmation
        } catch (e: any) {
          finalMessage += `\n\n❌ I tried to book that, but encountered an error: ${e.message}`;
        }
      } else if (result.action === 'CANCEL' && result.appointmentId) {
        try {
          await onCancel(result.appointmentId);
          finalMessage += '\n\n✅ I have successfully cancelled that appointment.';
        } catch (e: any) {
          finalMessage += `\n\n❌ I tried to cancel that, but encountered an error: ${e.message}`;
        }
      }

      setMessages(prev => [...prev, { role: 'assistant', text: finalMessage }]);

    } catch (error) {
      console.error("AI Error:", error);
      setMessages(prev => [...prev, { role: 'assistant', text: 'Sorry, I encountered an error processing your request.' }]);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="fixed bottom-6 right-6 z-50">
      {isOpen ? (
        <div className="bg-white w-80 sm:w-96 h-[500px] rounded-2xl shadow-2xl border border-neutral-200 flex flex-col overflow-hidden">
          <div className="bg-indigo-600 p-4 text-white flex justify-between items-center">
            <div className="flex items-center gap-2">
              <Bot className="w-5 h-5" />
              <h3 className="font-medium">AI Booking Assistant</h3>
            </div>
            <button onClick={() => setIsOpen(false)} className="text-indigo-100 hover:text-white transition-colors">
              <X className="w-5 h-5" />
            </button>
          </div>
          
          <div className="flex-1 overflow-y-auto p-4 space-y-4 bg-neutral-50">
            {messages.map((msg, idx) => (
              <div key={idx} className={`flex gap-3 ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}>
                <div className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 ${msg.role === 'user' ? 'bg-indigo-100 text-indigo-600' : 'bg-emerald-100 text-emerald-600'}`}>
                  {msg.role === 'user' ? <UserIcon className="w-4 h-4" /> : <Bot className="w-4 h-4" />}
                </div>
                <div className={`px-4 py-2 rounded-2xl max-w-[75%] text-sm whitespace-pre-wrap ${msg.role === 'user' ? 'bg-indigo-600 text-white rounded-tr-none' : 'bg-white border border-neutral-200 text-neutral-800 rounded-tl-none shadow-sm'}`}>
                  {msg.text}
                </div>
              </div>
            ))}
            {isLoading && (
              <div className="flex gap-3">
                <div className="w-8 h-8 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center shrink-0">
                  <Bot className="w-4 h-4" />
                </div>
                <div className="px-4 py-3 rounded-2xl bg-white border border-neutral-200 text-neutral-800 rounded-tl-none shadow-sm flex items-center gap-2">
                  <Loader2 className="w-4 h-4 animate-spin text-emerald-600" />
                  <span className="text-xs text-neutral-500 font-medium">Thinking...</span>
                </div>
              </div>
            )}
            <div ref={messagesEndRef} />
          </div>

          <div className="p-3 bg-white border-t border-neutral-200">
            <form 
              onSubmit={(e) => { e.preventDefault(); handleSend(); }}
              className="flex items-center gap-2"
            >
              <input
                type="text"
                value={input}
                onChange={(e) => setInput(e.target.value)}
                placeholder="Ask me to book a slot..."
                className="flex-1 bg-neutral-100 border-transparent focus:bg-white focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 rounded-full px-4 py-2 text-sm outline-none transition-all"
                disabled={isLoading}
              />
              <button 
                type="submit"
                disabled={!input.trim() || isLoading}
                className="bg-indigo-600 text-white p-2 rounded-full hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                <Send className="w-4 h-4" />
              </button>
            </form>
          </div>
        </div>
      ) : (
        <button
          onClick={() => setIsOpen(true)}
          className="bg-indigo-600 text-white p-4 rounded-full shadow-lg hover:bg-indigo-700 hover:scale-105 transition-all flex items-center gap-2"
        >
          <MessageSquare className="w-6 h-6" />
          <span className="font-medium pr-1">AI Assistant</span>
        </button>
      )}
    </div>
  );
}
